services:
  dev:
    image: mcmanager-dev
    container_name: mcmanager-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    user: 1000:1000
    volumes:
      - ..:/workdir
    environment:
      - TZ=Asia/Ho_Chi_Minh
    network_mode: bridge
